version: '3.8'

services:
  postgres:
    image: postgres:15 
    container_name: kanbandb
    restart: always
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kanbandb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: