// Generated by Copilot
import { AddIcon, CloseIcon } from '@/components/icons/icons';
import { AddCardButton, AppButton, AppButtonWithIcon, AppButtonWithIconSquared, CloseButton } from '../../components/button/AppButton';
import styles from './button-test-page.module.scss';

const ButtonTestPage = () => {
  return (
    <div className={styles.testPageContainer}>
      <div className={styles.testPageContent}>
        <h1 className={styles.heading}>Button Variations Test</h1>
        <div className={styles.sections}>
          <section>
            <h2 className={styles.sectionTitle}>AppButton Variants</h2>
            <div className={styles.buttonRow}>
              <AppButton variant="primary">Primary</AppButton>
              <AppButton variant="secondary">Secondary</AppButton>
              <AppButton variant="destructive">Destructive</AppButton>
            </div>
          </section>
          <section>
            <h2 className={styles.sectionTitle}>AppButton Sizes</h2>
            <div className={styles.buttonRow}>
              <AppButton size="large">Large</AppButton>
              <AppButton size="small">Small</AppButton>
            </div>
          </section>
          <section>
            <h2 className={styles.sectionTitle}>AppButtonWithIcon</h2>
            <div className={styles.buttonRow}>
              <AppButtonWithIcon icon={<AddIcon />}>With Icon</AppButtonWithIcon>
              <AppButtonWithIcon icon={<AddIcon />} variant="secondary">Secondary Icon</AppButtonWithIcon>
            </div>
          </section>
          <section>
            <h2 className={styles.sectionTitle}>AddCardButton</h2>
            <div className={styles.buttonRow}>
              <AddCardButton icon={<AddIcon />}>Add Card</AddCardButton>
            </div>
          </section>
          <section>
            <h2 className={styles.sectionTitle}>CloseButton</h2>
            <div className={styles.buttonRow}>
              <CloseButton icon={<CloseIcon />} />
            </div>
          </section>
          <section>
            <h2 className={styles.sectionTitle}>AppButtonWithIconSquared</h2>
            <div className={styles.buttonRow}>
              <AppButtonWithIconSquared icon={<AddIcon />}>Add Card</AppButtonWithIconSquared>
              <AppButtonWithIconSquared icon={<AddIcon />}>Secondary Action</AppButtonWithIconSquared>
            </div>
          </section>
          <section>
            <h2 className={styles.sectionTitle}>States (Idle/Hover)</h2>
            <p className={styles.statesNote}>Hover state can be seen by hovering over the buttons above.</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default ButtonTestPage;
